name: sd-api
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.19.2
  - pip:
      - diffusers
      - transformers==4.27.1
      - Pillow
      - Flask
      - flask_cors
      - accelerate
